<?php
    use OxcMP\Entity\Mod;
    
    /* @var $mod Mod  */
    /* @var $gitHubFlavoredMarkdownGuideUrl string */
    
    $this->headScript()->appendFile($this->url('home', [], ['force_canonical' => true]) . 'js/edit-mod.js');
    $modDescriptionHelpText = sprintf($this->translate('page_editmod_form_description_help'), $gitHubFlavoredMarkdownGuideUrl);
    


?>
<form name="editMod" id="editMod" class="p-2" action="<?php echo $this->url('save-mod',[], ['force_canonical' => true]) ?>" method="post" autocomplete="off" enctype="text/plain" novalidate data-slug-preview-action="<?php echo $this->url('preview-mod-slug',[], ['force_canonical' => true]) ?>" data-description-preview-action="<?php echo $this->url('preview-mod-description',[], ['force_canonical' => true]) ?>">
    <input type="hidden" name="id" id="id" value="<?php echo $mod->getId()->toString(); ?>"/>
    <div class="form-row">
        <div class="form-group col-sm-12 col-md-4">
            <label for="title"><?php echo $this->translate('page_editmod_form_title_title'); ?></label>
            <input class="form-control" type="text" name="title" id="title" aria-described-by="title-help" maxlength="64" placeholder="<?php echo $this->translate('page_editmod_form_title_placeholder'); ?>" value="<?php echo $this->escapeHtml($mod->getTitle()); ?>" />
            <small id="title-help" class="form-text text-muted"><?php echo $this->translate('page_editmod_form_title_help'); ?></small>
        </div>
        <div class="form-group col-sm-12 col-md-4">
            <label for="slug"><?php echo $this->translate('page_editmod_form_slug_title'); ?></label>
            <input class="form-control" type="text" name="slug" id="slug" aria-described-by="slug-help" placeholder="<?php echo $this->translate('page_editmod_form_slug_placeholder'); ?>" value="<?php echo $mod->getSlug(); ?>" disabled />
            <small id="slug-help" class="form-text text-muted"><?php echo $this->translate('page_editmod_form_slug_help'); ?></small>
        </div>
        <div class="form-group col-sm-12 col-md-4">
            <label><?php echo $this->translate('page_editmod_form_published_title'); ?></label>
            <div class="clearfix"></div>
            <div class="btn-group w-100" data-toggle="buttons" data-active-class="btn-primary" data-inactive-class="btn-secondary">
                <label class="btn w-50 <?php if ($mod->getIsPublished()) {echo 'btn-primary active';} else {echo 'btn-secondary';}?>">
                    <input type="radio" name="isPublished" value="1" <?php if ($mod->getIsPublished()) {echo 'checked';}?>> <?php echo $this->translate('page_editmod_form_published_yes'); ?>
                </label>
                <label class="btn w-50 <?php if (!$mod->getIsPublished()) {echo 'btn-primary active';} else {echo 'btn-secondary';}?>">
                    <input type="radio" name="isPublished" value="0" <?php if (!$mod->getIsPublished()) {echo 'checked';}?>> <?php echo $this->translate('page_editmod_form_published_no'); ?>
                </label>
            </div>
            <small id="slug-help" class="form-text text-muted"><?php echo $this->translate('page_editmod_form_published_help'); ?></small>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-12">
            <label for="summary"><?php echo $this->translate('page_editmod_form_summary_title'); ?></label>
            <textarea class="form-control font-monospace" name="summary" id="summary" aria-described-by="summary-help" maxlength="128" rows="3" placeholder="<?php echo $this->translate('page_editmod_form_summary_placeholder'); ?>"><?php echo $this->escapeHtml($mod->getSummary()); ?></textarea>
            <small id="summary-help" class="form-text text-muted"><?php echo $this->translate('page_editmod_form_summary_help'); ?></small>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-12">
            <nav class="nav nav-tabs" id="descriptions" role="tablist">
                <label class="nav-item pl-0 pt-2 pr-3"><?php echo $this->translate('page_editmod_form_description_title'); ?></label>
                <a class="nav-item nav-link active" id="description-edit-tab" data-toggle="tab" href="#description-edit" role="tab" aria-controls="description-edit" aria-expanded="true"><?php echo $this->translate('page_editmod_form_description_edit'); ?></a>
                <a class="nav-item nav-link" id="description-preview-tab" data-toggle="tab" href="#description-preview" role="tab" aria-controls="description-preview"><?php echo $this->translate('page_editmod_form_description_preview'); ?></a>
            </nav>
            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="description-edit" role="tabpanel" aria-labelledby="description-edit-tab">
                    <textarea class="form-control rounded-0 rounded-bottom font-monospace" name="descriptionRaw" id="descriptionRaw" aria-described-by="descriptionRaw-help" maxlength="65535" rows="20" placeholder="<?php echo $this->translate('page_editmod_form_description_placeholder'); ?>"><?php echo $this->escapeHtml($mod->getDescriptionRaw()); ?></textarea>
                    <small id="descriptionRaw-help" class="form-text text-muted"><?php echo $modDescriptionHelpText; ?></small>
                </div>
                <div class="tab-pane fade" id="description-preview" role="tabpanel" aria-labelledby="description-preview-tab">
                    <div id="description-preview-progress" class="py-4 d-none">
                        <div class="progress w-100">
                            <div class="progress-bar progress-bar-striped progress-bar-animated w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                    <div id="description-preview-content" class="h-100 overflow-y-auto"><?php echo $mod->getDescription(); echo PHP_EOL; ?></div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-sm-12 col-md-6">
        </div>
        <div class="form-group col-sm-12 col-md-6">
        </div>
    </div>
    <div class="modal-footer">
        <div id="progress" class="progress w-100 d-none">
            <div class="progress-bar progress-bar-striped progress-bar-animated w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <div id="error-message" class="alert alert-warning m-0 mr-2 p-1 w-100 text-center d-none">Some error text</div>
        <button type="submit" class="btn btn-primary"><?php echo $this->translate('page_editmod_form_btn_submit') ?></button>
        <button type="button" class="btn btn-danger"><?php echo $this->translate('page_editmod_form_btn_delete') ?></button>
    </div>
</form>