<?php

    /* @var $config \Zend\Config\Config */
    /* @var $mod \OxcMP\Entity\Mod  */
    /* @var $modBackground \OxcMP\Entity\ModFile  */
    /* @var $modImage \OxcMP\Entity\ModFile */
    /* @var $tag \OxcMP\Entity\Tag  */
    /* @var $modTag \OxcMP\Entity\ModTag  */
    /* @var $gitHubFlavoredMarkdownGuideUrl string */
    
    $this->headScript()->appendFile($this->url('home', [], ['force_canonical' => true]) . 'js/edit-mod.js');
    
    // "Extract" some variables from the config
    $gitHubFlavoredMarkdownGuideUrl = $config->layout->gitHubFlavoredMarkdownGuideUrl;
    $backgroundWidth = $config->storage->background->width;
    $backgroundHeight = $config->storage->background->height;
    $chunkSize = $config->upload->chunkSize * 1024 * 1024; // This needs to be in bytes
    $maxImageSize = $config->storage->maxFileSize->image;
    $maxResourceSize = $config->storage->maxFileSize->resource;
    
    $modDescriptionHelpText = sprintf($this->translate('page_editmod_form_description_help'), $gitHubFlavoredMarkdownGuideUrl);
    
    $availableTagNames = [];
    foreach ($tags as $tag) {
        $availableTagNames[] = $tag->getTag();
    }
    
    $selectedTagNames = [];
    foreach ($modTags as $modTag) {
        $selectedTagNames[] = $modTag->getTag();
    }
    
    $backgroundImageDefaultUrl = $this->staticUrl('img/bg-default.png');
    $backgroundImageInstructionsUrl = $this->staticUrl('img/bg-instructions.png');
    $backgroundSupportArchiveUrl = $this->staticUrl('resources/background-support.zip');
    
    $backgroundDefaultUrl = $this->defaultBackgroundUrl();
    $backgroundUrl = $this->modBackgroundUrl($mod, $modBackground);
    $backgroundUuid = ($modBackground instanceof \OxcMP\Entity\ModFile) ? $modBackground->getId()->toString() : '';
    
    // Some translations that are needed by JS
    // TODO: Embed them in a json somewhere?
    $jsLangKeys = [
        'global_unexpected_error',
        'global_chunk_upload_unsupported',
        'page_editmod_success_background',
        'page_editmod_success_background_default',
        'page_editmod_error_multi_upload_abort',
        'page_editmod_error_multi_upload_failure',
        'page_editmod_success_multi_upload',
        'page_editmod_error_file_upload_abort',
        'page_editmod_error_file_upload_retry',
    ];
    
    $jsLang = [];
    foreach ($jsLangKeys as $jsLangKey) {
        $jsLang[$jsLangKey] = $this->translate($jsLangKey);
    }

?>
<form 
    name="editMod"
    id="editMod"
    class="p-2"
    action="<?php echo $this->url('save-mod', ['modUuid' => $mod->getId()->toString()], ['force_canonical' => true]); ?>"
    method="post"
    autocomplete="off"
    enctype="text/plain"
    novalidate
    data-slug-preview-action="<?php echo $this->url('preview-mod-slug', ['modUuid' => $mod->getId()->toString()], ['force_canonical' => true]); ?>"
    data-description-preview-action="<?php echo $this->url('preview-mod-description', ['modUuid' => $mod->getId()->toString()], ['force_canonical' => true]); ?>"
    data-create-upload-slot-action="<?php echo $this->url('create-upload-slot', ['modUuid' => $mod->getId()->toString()], ['force_canonical' => true]); ?>"
    data-upload-file-chunk-action="<?php echo $this->url('upload-file-chunk', ['modUuid' => $mod->getId()->toString()], ['force_canonical' => true]); ?>"
    data-validate-mod-file-action="<?php echo $this->url('validate-mod-file', [], ['force_canonical' => true]); ?>"
    data-chunk-size="<?php echo $chunkSize; ?>"
>
    <script> var Lang = <?php echo json_encode($jsLang); ?>; </script>
    <div class="form-row">
        <div class="form-group col-sm-12 col-md-4">
            <label for="title"><?php echo $this->translate('page_editmod_form_title_title'); ?></label>
            <input class="form-control" type="text" name="title" id="title" aria-described-by="title-help" maxlength="64" placeholder="<?php echo $this->translate('page_editmod_form_title_placeholder'); ?>" value="<?php echo $this->escapeHtml($mod->getTitle()); ?>" />
            <small id="title-help" class="form-text text-muted"><?php echo $this->translate('page_editmod_form_title_help'); ?></small>
        </div>
        <div class="form-group col-sm-12 col-md-4">
            <label for="slug"><?php echo $this->translate('page_editmod_form_slug_title'); ?></label>
            <input class="form-control" type="text" name="slug" id="slug" aria-described-by="slug-help" placeholder="<?php echo $this->translate('page_editmod_form_slug_placeholder'); ?>" value="<?php echo $mod->getSlug(); ?>" disabled />
            <small id="slug-help" class="form-text text-muted"><?php echo $this->translate('page_editmod_form_slug_help'); ?></small>
        </div>
        <div class="form-group col-sm-12 col-md-4">
            <label><?php echo $this->translate('page_editmod_form_published_title'); ?></label>
            <div class="clearfix"></div>
            <div class="btn-group btn-group-toggle w-100" data-toggle="buttons" data-active-class="btn-primary" data-inactive-class="btn-secondary">
                <label class="btn w-50 <?php if ($mod->getIsPublished()) {echo 'btn-primary active';} else {echo 'btn-secondary';}?>">
                    <input type="radio" name="isPublished" value="1" <?php if ($mod->getIsPublished()) {echo 'checked';}?>> <?php echo $this->translate('page_editmod_form_published_yes'); ?>
                </label>
                <label class="btn w-50 <?php if (!$mod->getIsPublished()) {echo 'btn-primary active';} else {echo 'btn-secondary';}?>">
                    <input type="radio" name="isPublished" value="0" <?php if (!$mod->getIsPublished()) {echo 'checked';}?>> <?php echo $this->translate('page_editmod_form_published_no'); ?>
                </label>
            </div>
            <small id="slug-help" class="form-text text-muted"><?php echo $this->translate('page_editmod_form_published_help'); ?></small>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-12">
            <label for="summary"><?php echo $this->translate('page_editmod_form_summary_title'); ?></label>
            <textarea class="form-control font-monospace" name="summary" id="summary" aria-described-by="summary-help" maxlength="128" rows="3" placeholder="<?php echo $this->translate('page_editmod_form_summary_placeholder'); ?>"><?php echo $this->escapeHtml($mod->getSummary()); ?></textarea>
            <small id="summary-help" class="form-text text-muted"><?php echo $this->translate('page_editmod_form_summary_help'); ?></small>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-12">
            <nav class="nav nav-tabs" id="descriptions" role="tablist">
                <label class="nav-item pl-0 pt-2 pr-3"><?php echo $this->translate('page_editmod_form_description_title'); ?></label>
                <a class="nav-item nav-link active" id="description-edit-tab" data-toggle="tab" href="#description-edit" role="tab" aria-controls="description-edit" aria-expanded="true"><?php echo $this->translate('page_editmod_form_description_edit'); ?></a>
                <a class="nav-item nav-link" id="description-preview-tab" data-toggle="tab" href="#description-preview" role="tab" aria-controls="description-preview"><?php echo $this->translate('page_editmod_form_description_preview'); ?></a>
            </nav>
            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="description-edit" role="tabpanel" aria-labelledby="description-edit-tab">
                    <textarea class="form-control rounded-0 rounded-bottom font-monospace" name="descriptionRaw" id="descriptionRaw" aria-described-by="descriptionRaw-help" maxlength="65535" rows="20" placeholder="<?php echo $this->translate('page_editmod_form_description_placeholder'); ?>"><?php echo $this->escapeHtml($mod->getDescriptionRaw()); ?></textarea>
                    <small id="descriptionRaw-help" class="form-text text-muted"><?php echo $modDescriptionHelpText; ?></small>
                </div>
                <div class="tab-pane fade border p-2" id="description-preview" role="tabpanel" aria-labelledby="description-preview-tab">
                    <div id="description-preview-progress" class="py-4 d-none">
                        <div class="progress w-100">
                            <div class="progress-bar progress-bar-striped progress-bar-animated w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                    <div id="description-preview-content" class="h-100 overflow-y-auto"><?php echo $mod->getDescription(); echo PHP_EOL; ?></div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-sm-12 col-md-6">
            <label><?php echo $this->translate('page_editmod_form_tags_selected_title')?></label>
            <div id="tag-select-none" class="form-text text-muted pl-3 pt-1 pb-2 d-none">
                <?php echo $this->translate('page_editmod_form_tags_selected_none'); ?>
            </div>
            <div id="tag-select" class="pb-1" data-selected="<?php echo implode(',', $selectedTagNames); ?>">
                <a href="#" name="my-tag" class="badge badge-primary p-2 mb-2 mr-2">my-tag</a>
            </div>
            <small class="form-text text-muted"><?php echo $this->translate('page_editmod_form_tags_selected_help'); ?></small>
        </div>
        <div class="form-group col-sm-12 col-md-6">
            <label for="tag-search"><?php echo $this->translate('page_editmod_form_tags_search_title'); ?></label>
            <input class="form-control" type="text" id="tag-search" aria-described-by="tag-search-help" placeholder="<?php echo $this->translate('page_editmod_form_tags_search_placeholder'); ?>" data-available="<?php echo implode(',', $availableTagNames);?>" />
            <div id="tag-search-result" class="d-none">
                <div class="border rounded px-2 pt-2">
                    <a href="#" name="my-tag" class="badge badge-primary p-2 mr-2 mb-2">my-tag</a>
                </div>
            </div>
            <small id="tag-search-help" class="form-text text-muted"><?php echo $this->translate('page_editmod_form_tags_search_help'); ?></small>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-sm-12 col-md-6">
            <label><?php echo $this->translate('page_editmod_form_background_current_title'); ?></label>
            <img id="background-image" class="img-fluid" src="<?php echo $backgroundUrl; ?>" data-background-uuid="<?php echo $backgroundUuid; ?>" data-default-background-url="<?php echo $backgroundDefaultUrl; ?>"  alt="<?php echo $this->translate('page_editmod_image_background_alt')?>">
            <input id="background-image-upload" accept="image/*" class="d-none" type="file" />
        </div>
        <div class="form-group col-sm-12 col-md-6">
            <label><?php echo $this->translate('page_editmod_form_background_manage_title'); ?></label>
            <small class="form-text text-muted"><?php echo $this->translate('page_editmod_form_background_manage_help_intro'); ?></small>
            <div>
                <img class="img-fluid" src="<?php echo $backgroundImageInstructionsUrl?>" alt="<?php echo $this->translate('page_editmod_image_background_process_alt')?>">
            </div>
            <div class="container p-0">
                <div class="row">
                    <div class="col">
                        <div class="small form-text text-muted">
                            <ol start="1" class="pl-3">
                                <li><?php echo $this->translate('page_editmod_form_background_manage_help_1'); ?></li>
                            </ol>
                        </div>
                    </div>
                    <div class="col">
                        <div class="small form-text text-muted">
                            <ol start="2" class="pl-3">
                                <li><?php echo $this->translate('page_editmod_form_background_manage_help_2'); ?></li>
                            </ol>
                        </div>
                    </div>
                    <div class="col">
                        <div class="small form-text text-muted">
                            <ol start="3" class="pl-2">
                                <li><?php echo $this->translate('page_editmod_form_background_manage_help_3'); ?></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer border-top-0 p-0">
                <div id="background-progress" class="progress w-100 d-none">
                    <div class="progress-bar progress-bar-striped progress-bar-animated" style="width:0%" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <div id="background-message" class="alert alert-warning m-0 mr-2 p-1 w-100 text-center d-none">Some message text</div>
                <button type="button" id="upload-background" class="btn btn-primary"><?php echo $this->translate('page_editmod_form_background_manage_btn_upload'); ?></button>
                <button type="button" id="default-background" class="btn btn-danger" disabled data-toggle="modal" data-target="#default-background-modal"><?php echo $this->translate('page_editmod_form_background_manage_btn_default'); ?></button>
            </div>
            <small class="form-text text-muted"><?php echo sprintf($this->translate('page_editmod_form_background_manage_help_technical'), $backgroundWidth, $backgroundHeight, $maxImageSize, $backgroundSupportArchiveUrl); ?></small>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-12">
            <div id="image-card-sample" class="d-none">
                <?php echo $this->partial('oxc-mp/mod-management/partial/card-image.phtml') . PHP_EOL; ?>
            </div>
            <label><?php echo $this->translate('page_editmod_form_gallery_title'); ?></label>
            <div id="image-list" class="row">
                <?php
                    foreach ($modImages as $modImage) {
                        $parameters = [
                            'mod' => $mod,
                            'modImage' => $modImage,
                            'config' => $config
                        ];
                        echo $this->partial('oxc-mp/mod-management/partial/card-image.phtml', $parameters) . PHP_EOL;
                    }
                    
                    echo $this->partial('oxc-mp/mod-management/partial/card-image-upload.phtml') . PHP_EOL;
                ?>
            </div>
            <small id="gallery-help" class="form-text text-muted"><?php echo sprintf($this->translate('page_editmod_form_gallery_help'), $maxImageSize); ?></small>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-12">
            <div id="resource-card-sample" class="d-none">
                <?php echo $this->partial('oxc-mp/mod-management/partial/card-resource.phtml') . PHP_EOL; ?>
            </div>
            <label><?php echo $this->translate('page_editmod_form_resources_title'); ?></label>
            <div id="resource-list" class="row">
                <?php
                    foreach ($modResources as $modResource) {
                        $parameters = [
                            'mod' => $mod,
                            'modResource' => $modResource
                        ];
                        echo $this->partial('oxc-mp/mod-management/partial/card-resource.phtml', $parameters) . PHP_EOL;
                    }

                    echo $this->partial('oxc-mp/mod-management/partial/card-resource-upload.phtml') . PHP_EOL;
                ?>
            </div>
            <small id="gallery-help" class="form-text text-muted"><?php echo sprintf($this->translate('page_editmod_form_resources_help'), $maxResourceSize); ?></small>
        </div>
    </div>
    <div class="modal-footer">
        <div id="progress" class="progress w-100 d-none">
            <div class="progress-bar progress-bar-striped progress-bar-animated w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <div id="error-message" class="alert alert-warning m-0 mr-2 p-1 w-100 text-center d-none">Some error text</div>
        <button type="submit" class="btn btn-primary"><?php echo $this->translate('page_editmod_form_btn_submit') ?></button>
        <button type="button" class="btn btn-danger"><?php echo $this->translate('page_editmod_form_btn_delete') ?></button>
    </div>
</form>
<?php
    // Associated modals
     echo $this->partial('oxc-mp/mod-management/partial/modal-default-background.phtml') . PHP_EOL;
     echo $this->partial('oxc-mp/mod-management/partial/modal-multi-upload.phtml') . PHP_EOL;
     echo $this->partial('oxc-mp/mod-management/partial/modal-edit-file.phtml') . PHP_EOL;
