<?php
    $this->headScript()->appendFile($this->url('home', [], ['force_canonical' => true]) . 'js/lang/my-mods.js');
    $this->headScript()->appendFile($this->url('home', [], ['force_canonical' => true]) . 'js/my-mods.js');
?>
<div class="row">
<?php
    // List all mods
    foreach ($mods as $mod) {
        echo $this->partial('oxc-mp/mod-management/partial/card-mod.phtml', ['mod' => $mod, 'config' => $config]);
        echo PHP_EOL;
    }
    
    echo PHP_EOL;
    
    // Add "add new mod" card last
    echo $this->partial('oxc-mp/mod-management/partial/card-mod-new.phtml');

?>
</div>
<?php
    echo $this->partial('oxc-mp/mod-management/partial/modal-mod-new.phtml');