<div class="col-sm-6 col-md-4 col-lg-3">
    <div class="card m-2">
        <img class="card-img-top" src="<?php echo $this->staticUrl('img/mod-add-image.svg'); ?>" alt="<?php echo $this->translate('page_editmod_form_gallery_add'); ?>">
        <div class="card-footer text-right">
            <button type="button" id="add-image" class="btn btn-primary"><?php echo $this->translate('page_editmod_form_gallery_add'); ?></button>
        </div>
    </div>
    <input id="upload-image" type="file" class="d-none" multiple accept="image/*"/>
</div>