<div class="col-sm-6 col-md-4 col-lg-3">
    <div class="card m-2">
        <img class="card-img-top" src="<?php echo $this->staticUrl('img/mod-add-resource.svg'); ?>" alt="<?php echo $this->translate('page_editmod_form_resources_add'); ?>">
        <div class="card-footer text-right">
            <button type="button" id="add-resource" class="btn btn-primary"><?php echo $this->translate('page_editmod_form_resources_add'); ?></button>
        </div>
    </div>
    <input id="upload-resource" type="file" class="d-none" multiple accept="application/zip"/>
</div>
<!--<div class="col-sm-6 col-md-4 col-lg-3">
    <div class="card m-2">
        <img class="card-img-top" src="<?php echo $this->staticUrl('img/mod-add-resource.svg'); ?>" alt="<?php echo $this->translate('page_editmod_form_resources_add'); ?>">
        <div class="card-footer text-right">
            <button type="button" id="add-resource" class="btn btn-primary"><?php echo $this->translate('page_editmod_form_resources_add'); ?></button>
        </div>
    </div>
</div>-->