<div class="modal fade" id="default-background-modal" tabindex="-1" role="dialog" aria-labelledby="default-background-title" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="default-background-title"><?php echo $this->translate('page_editmod_background_default'); ?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo $this->translate('global_close'); ?>">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <?php echo $this->translate('page_editmod_background_default_help'); ?>
            </div>
            <div class="modal-footer">
                <button type="button" id="use-default-background" class="btn btn-danger" data-dismiss="modal"><?php echo $this->translate('page_editmod_background_default_use'); ?></button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php echo $this->translate('global_close'); ?></button>
            </div>
        </div>
    </div>
</div>