<div class="modal fade" id="multi-upload" tabindex="-1" role="dialog" aria-labelledby="multi-upload-title" aria-hidden="true">
    <div id="file-card-sample" class="d-none">
        <div class="card">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">FileName</li>
                <li class="list-group-item">
                    <div class="progress w-100">
                        <div class="progress-bar progress-bar-striped progress-bar-animated w-0 text-center" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="multi-upload-title"><?php echo $this->translate('page_editmod_form_upload_modal_title'); ?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo $this->translate('global_close'); ?>">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                File list
            </div>
            <div class="modal-footer">
                <div class="progress w-100">
                    <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <div class="alert alert-warning m-0 mr-2 p-1 w-100 text-center">Message</div>
                <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php echo $this->translate('global_close') ?></button>
                <button type="button" class="btn btn-danger"><?php echo $this->translate('page_editmod_form_upload_modal_abort'); ?></button>
            </div>
        </div>
    </div>
</div>