<?php
    // Icons and code partially generated using https://realfavicongenerator.net/
    
    $homeUrl = $this->staticUrl();
    $appTitle = $this->translate('global_application_name');
?>
<link rel="apple-touch-icon" sizes="180x180" href="<?php echo $homeUrl ?>apple-touch-icon.png">
<link rel="icon" type="image/png" href="<?php echo $homeUrl ?>favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="<?php echo $homeUrl ?>android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="<?php echo $homeUrl ?>favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="<?php echo $homeUrl ?>manifest.json">
<link rel="mask-icon" href="<?php echo $homeUrl ?>safari-pinned-tab.svg" color="#0076d9">
<meta name="apple-mobile-web-app-title" content="<?php echo $appTitle ?>">
<meta name="application-name" content="<?php echo $appTitle ?>">
<meta name="msapplication-TileColor" content="#0076d9">
<meta name="msapplication-TileImage" content="<?php echo $homeUrl ?>mstile-144x144.png">
<meta name="theme-color" content="#0076d9">