<?php
    $this->headScript()->appendFile('js/my-mods.js');
?>
<div class="row">
<?php
    // Add "add new mod" card first

    echo $this->placeholder('card-mod-new')
        ->setIndent(4)
        ->set(
            $this->partial('oxc-mp/mod/partial/card-mod-new.phtml')
        );

    echo PHP_EOL;

    foreach ($mods as $mod) {
        echo $this->placeholder('card-mod')
            ->setIndent(4)
            ->set(
                $this->partial('oxc-mp/mod/partial/card-mod.phtml', ['mod' => $mod])
            );
        
        echo PHP_EOL;
    }
?>
</div>
<?php
    echo $this->placeholder('modal-mod-new')
        ->set(
            $this->partial('oxc-mp/mod/partial/modal-mod-new.phtml')
        );