<?php echo $this->doctype() . PHP_EOL ?>
<html lang="en">
    <head>
<?php
    echo $this->headTitle($this->translate('global_application_name'))
        ->setIndent(8)
        ->setSeparator(' :: ')
        ->setAutoEscape(false);

    echo PHP_EOL;
    
    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')
        ->appendName('charset', 'utf-8')
        ->setIndent(8)
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

    echo PHP_EOL;
    
    // Add CSS
    $bootstrapMinCss = $this->config->layout->css->bootstrapMin;
    echo $this->headLink()
        ->setIndent(8)
        ->appendStylesheet(
            $bootstrapMinCss->href,
            'screen',
            '',
            ['integrity' => $bootstrapMinCss->integrity, 'crossorigin' => $bootstrapMinCss->crossorigin]
        )
        ->appendStylesheet('css/style.css');
    
    echo PHP_EOL;
?>
    </head>
    <body style="background: url('<?php echo $this->defaultBackground ?>') top center no-repeat">
        <div class="container">
<?php 
    echo $this->placeholder('mainmenu')
        ->setIndent(12)
        ->set($this->mainMenu()->render(false));
    
    echo PHP_EOL;
?>
<?php echo $this->placeholder('content')->set($this->content)->setIndent(12) . PHP_EOL ?>
        </div>
<?php
    //Login modal, only if not logged in
    if (true) {
        echo $this->placeholder('loginmodal')
            ->setIndent(8)
            ->set(
                $this->modal()->renderLoginModal($this->config->layout->oAuthUrl)
            );
        echo PHP_EOL;
    }
?>
<?php
    // Add JS
    $jquerySlimMinJs = $this->config->layout->js->jquerySlimMin;
    $tetherMinJs = $this->config->layout->js->tetherMin;
    $bootstrapMinJs = $this->config->layout->js->bootstrapMin;
    echo $this->headScript()
        ->setIndent(8)
        ->setAllowArbitraryAttributes(true) // This is needed for the "integrity" attribute, which is not supported as of Feb 2017
        ->appendFile($jquerySlimMinJs->src, 'text/javascript', ['integrity' => $jquerySlimMinJs->integrity, 'crossorigin' => $jquerySlimMinJs->crossorigin])
        ->appendFile($tetherMinJs->src, 'text/javascript', ['integrity' => $tetherMinJs->integrity, 'crossorigin' => $tetherMinJs->crossorigin])
        ->appendFile($bootstrapMinJs->src, 'text/javascript', ['integrity' => $bootstrapMinJs->integrity, 'crossorigin' => $bootstrapMinJs->crossorigin]);
    
    echo PHP_EOL;
?>
    </body>
</html>
