<?= $this->doctype() ?>

<html lang="en">
    <head>
        <?php
        
            echo $this->headTitle('OpenXcom Mod Portal')->setSeparator(' - ')->setAutoEscape(false);

            echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')
                ->appendName('charset', 'utf-8')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge') . PHP_EOL;

            // Add CSS
            $bootstrapMinCss = $this->config->layout->css->bootstrapMin;
            echo $this->headLink()
                      ->appendStylesheet($bootstrapMinCss->href, 'screen', '', ['integrity' => $bootstrapMinCss->integrity, 'crossorigin' => $bootstrapMinCss->crossorigin]);
        ?>
    </head>
    <body>
        
        <?= $this->content ?>
        
        <?php
            // Add JS
            $jquerySlimMinJs = $this->config->layout->js->jquerySlimMin;
            $tetherMinJs = $this->config->layout->js->tetherMin;
            $bootstrapMinJs = $this->config->layout->js->bootstrapMin;
            echo $this->headScript()
                ->setAllowArbitraryAttributes(true) // This is needed for the "integrity" attribute, which is not supported as of Feb 2017
                ->appendFile($jquerySlimMinJs->src, 'text/javascript', ['integrity' => $jquerySlimMinJs->integrity, 'crossorigin' => $jquerySlimMinJs->crossorigin])
                ->appendFile($tetherMinJs->src, 'text/javascript', ['integrity' => $tetherMinJs->integrity, 'crossorigin' => $tetherMinJs->crossorigin])
                ->appendFile($bootstrapMinJs->src, 'text/javascript', ['integrity' => $bootstrapMinJs->integrity, 'crossorigin' => $bootstrapMinJs->crossorigin]);
        ?>
    </body>
</html>






<?php return ?>

<!--
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Zend Framework <?= \OxcMP\Module::VERSION ?>"/>&nbsp;Skeleton Application
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('home') ?>">Home</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
-->
