<?php
     /* @var $mod \OxcMP\Entity\Mod */
?>
<div class="col-sm-6 col-md-4 col-lg-3">
    <div class="card m-2">
        <img class="card-img-top" src="img/logo.svg" alt="Add new mod">
        <div class="card-body">
            <h4 class="card-title">Add new mod</h4>
            <p class="card-text">Add new mod description</p>
        </div>
        <div class="card_footer">
            <a class="btn btn-primary" href="/add">Add</a>
        </div>
    </div>
</div>