<div class="modal fade" id="modNewModal" tabindex="-1" role="dialog" aria-labelledby="modNewModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form name="createMod" id="createMod" action="<?php echo $this->url('add-mod',[], ['force_canonical' => true]) ?>" method="post" autocomplete="off" enctype="text/plain" novalidate>
                <div class="modal-header">
                    <h5 class="modal-title" id="modNewModalLabel"><?php echo $this->translate('page_mymods_create_modal_title') ?></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo $this->translate('global_close') ?>">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                      <label for="modTitle"><?php echo $this->translate('page_mymods_create_modal_mod_title_title') ?></label>
                      <input type="text" class="form-control" name="modTitle" aria-describedby="modTitleHelp" placeholder="<?php echo $this->translate('page_mymods_create_modal_mod_title_placeholder') ?>" required>
                      <small id="modTitleHelp" class="form-text text-muted"><?php echo $this->translate('page_mymods_create_modal_mod_title_help') ?></small>
                      <div class="invalid-feedback"></div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="progress w-100 d-none">
                        <div class="progress-bar progress-bar-striped progress-bar-animated w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <div class="alert alert-warning m-0 mr-2 p-1 w-100 text-center d-none"></div>
                    <button type="submit" class="btn btn-primary"><?php echo $this->translate('page_mymods_create_modal_submit') ?></button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php echo $this->translate('global_close') ?></button>
                </div>
            </form>
        </div>
    </div>
</div>